apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: non-admin-controller-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oadp-operator
    app.kubernetes.io/part-of: oadp-operator
    app.kubernetes.io/managed-by: kustomize
  name: non-admin-controller
  namespace: system
