name: go-tests
on:
  push:
    paths:
      - '**/**.go'
      - '**/go.mod'
      - '.github/workflows/go-tests.yml'
      - '**/Dockerfile'
      - 'Makefile'
  pull_request:
    paths:
      - '**/**.go'
      - '**/go.mod'
      - '.github/workflows/go-tests.yml'
      - '**/Dockerfile'
      - 'Makefile'
  workflow_dispatch:
jobs:
  make-test_submitcoverage: #test and submit coverage to codecov on pushes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18' # The Go version to download (if necessary) and use.
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go version
    - name: submit test coverage
      run: make test submit-coverage
  podman-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: podman build .